name: Display folder structure
on: [push]

jobs:
  tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: cat test.text
        run: cat test.text