name: Display folder structure
on: [push]

jobs:
  tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree
      - name: Display folder structure
        run: tree